### ISSUE TITLE
Web site logo

### ISSUE THREAD

**Issue by Loki1950** [vegastrike/vegastrike.github.io#1]
A bit a decision to make use the old oval logo or the newer banner style one

**Comment by nabaco** [comment]
+1 for using the new banner style one. Just give me a bigger version with transparency, and I'll put it on the website

**Comment by nabaco** [comment]
Logo switched. It indeed looks better.
I'm loading the old website zip file here for record sake. I wish to keep it away from the repo history, as to keep it as small as possible.
[vegastrike-webpage-masters.zip](https://github.com/vegastrike/vegastrike.github.io/files/4570284/vegastrike-webpage-masters.zip)

Now I want the navigation icon (the one on the left side of the top navigation bar) to be transparent, and to update the favicon.ico so it'll be consistent with the others. (that's the one you see at your browser's tab).

**Comment by pyramid3d** [comment]
Seems the master file for the logo on top left (VS with three/part shape) is lost on me.
I did commit all the masters for logo and icons I found. https://github.com/vegastrike/Assets-Masters/tree/master/logo
