### ISSUE TITLE
Add list of contributors/sponsors/backers to the website

### ISSUE THREAD

**Issue by nabaco** [vegastrike/vegastrike.github.io#12]
We need to add a list of all the contributors/backers/sponsors on the website (as promised). My only dilemma here is whether to add it to the main page, or open a separate page for it.

We could add a separate page that will detail out all the different ways to contribute to the project, and I'll move the info there from the about page, and on the page to have the list.

Or we could have it on the main page, giving it much more notice.

**Comment by nabaco** [comment]
@vegastrike/vegastrike-infrastructure-admins I'd like to hear your opinion on this

**Comment by BenjamenMeyer** [comment]
So usually top contributors get a spot on the main page and everyone gets a spot on a secondary page

**Comment by nabaco** [comment]
Currently we don't have "top" and not "top" contributors, but point taken for future reference

**Comment by Loki1950** [comment]
I prefer a secondary page and a top monthly contributor on the main which could be taken care of by script parsing our commits here on GitHub.

**Comment by BenjamenMeyer** [comment]
@nabaco presently with the size of the group of contributors/sponsors they probably all fit on the main page right now; as it grows we can adjust.

**Comment by stephengtuggy** [comment]
This list has been implemented, hasn't it? Can this ticket be closed?
